# Generated by Django 2.1.4 on 2020-11-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20201108_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='posted_by',
        ),
    ]
