# Generated by Django 2.1.4 on 2020-11-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_remove_link_posted_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
    ]
