# Generated by Django 2.1.4 on 2020-11-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_link_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
